(function(root){
  "use strict";
  const {CURRENCIES,convertCurrency,parseAmount}=root.CurrencyWords;
  const LOCALIZATION={USD:["English","english"],EUR:["French","french"],GBP:["English","english"],CAD:["French","french"],AUD:["English","english"],JPY:["Japanese","japanese"],CNY:["Simplified Chinese","chinese"],INR:["Hindi","hindi"],CHF:["German","german"],SGD:["English","english"],KRW:["Korean","korean"],AED:["Arabic","arabic"],BHD:["Arabic","arabic"]};
  Object.entries(LOCALIZATION).forEach(([k,v])=>LOCALIZATION[k]={language:v[0],kind:v[1]});
  const D={chinese:["零","一","二","三","四","五","六","七","八","九"],japanese:["零","一","二","三","四","五","六","七","八","九"],korean:["영","일","이","삼","사","오","육","칠","팔","구"]};
  const SMALL={chinese:["","十","百","千"],japanese:["","十","百","千"],korean:["","십","백","천"]};
  const LARGE={chinese:["","万","亿","兆","京"],japanese:["","万","億","兆","京"],korean:["","만","억","조","경"]};
  function cjkGroup(n,kind,leading){let r="",zero=false;for(let p=3;p>=0;p--){const x=Math.floor(n/10**p)%10;if(!x){if(r&&n%10**p)zero=true;continue;}if(zero&&kind==="chinese")r+=D[kind][0];zero=false;if(!(x===1&&p>0&&(kind!=="chinese"||leading&&!r)))r+=D[kind][x];r+=SMALL[kind][p];}return r;}
  function cjkInteger(value,kind){let n=BigInt(value);if(!n)return D[kind][0];const groups=[];while(n){groups.push(Number(n%10000n));n/=10000n;}let r="",bridge=false;for(let i=groups.length-1;i>=0;i--){const g=groups[i];if(!g){if(r)bridge=true;continue;}if(kind==="chinese"&&r&&(bridge||g<1000))r+=D[kind][0];r+=cjkGroup(g,kind,!r)+LARGE[kind][i];bridge=false;}return r;}
  function koreanComma(value){const digits=BigInt(value).toString();if(digits==="0")return"영";let r="";for(let i=0;i<digits.length;i++){const x=Number(digits[i]),pos=digits.length-i-1,small=pos%4,large=Math.floor(pos/4);if(x){if(!(x===1&&small>0))r+=D.korean[x];r+=SMALL.korean[small];}if(small===0&&large>0&&/[1-9]/.test(digits.slice(Math.max(0,i-3),i+1)))r+=LARGE.korean[large];if(i<digits.length-1&&(digits.length-i-1)%3===0&&r&&!r.endsWith(","))r+=",";}return r.replace(/,+$/,"");}
  function westernLocal(a,code){const names={EUR:["euro","euros","centime","centimes"],CAD:["dollar canadien","dollars canadiens","cent","cents"],CHF:["Schweizer Franken","Schweizer Franken","Rappen","Rappen"],INR:["भारतीय रुपया","भारतीय रुपये","पैसा","पैसे"],AED:["درهم إماراتي","درهم إماراتي","فلس","فلس"],BHD:["دينار بحريني","دينار بحريني","فلس","فلس"]};const n=names[code];const lang=LOCALIZATION[code].kind;const number=(v)=>new Intl.NumberFormat(LOCALIZATION[code].language==="French"?(code==="CAD"?"fr-CA":"fr-FR"):lang==="german"?"de-CH":lang==="hindi"?"hi-IN":"ar",{useGrouping:true}).format(v);return `${a.negative?(lang==="arabic"?"سالب ":lang==="hindi"?"ऋण ":lang==="french"?"moins ":"minus "):""}${number(a.major)} ${a.major===1n?n[0]:n[1]}${a.minor?` ${lang==="arabic"?"و":lang==="hindi"?"और":lang==="french"?"et":"und"} ${number(a.minor)} ${a.minor===1n?n[2]:n[3]}`:""}`;}
  function localizedCurrency(input,code){const c=CURRENCIES[code],l=LOCALIZATION[code];if(!c||!l)throw new TypeError("Choose a supported currency.");const a=parseAmount(input,c.precision);if(!a)return{language:l.language,text:""};let text;if(l.kind==="english")text=convertCurrency(input,code);else if(l.kind==="korean")text=`${a.negative?"마이너스 ":""}${koreanComma(a.major)} 원`;else if(l.kind==="japanese")text=`${a.negative?"マイナス":""}${cjkInteger(a.major,"japanese")}円`;else if(l.kind==="chinese"){const j=a.minor/10n,f=a.minor%10n;text=`${a.negative?"负":""}${cjkInteger(a.major,"chinese")}元${j?D.chinese[Number(j)]+"角":""}${f?D.chinese[Number(f)]+"分":""}${!a.minor?"整":""}`;}else text=westernLocal(a,code);return{language:l.language,text};}
  root.LocalizedCurrencyWords={LOCALIZATION,cjkInteger,koreanIntegerWithThousandsCommas:koreanComma,localizedCurrency};
  if(typeof module!=="undefined")module.exports=root.LocalizedCurrencyWords;
})(typeof globalThis!=="undefined"?globalThis:this);
